// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VideoStoreManagementApi.Contexts;

#nullable disable

namespace VideoStoreManagementApi.Migrations
{
    [DbContext(typeof(VideoStoreContext))]
    [Migration("20240530162933_updated-videoModel")]
    partial class updatedvideoModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("VideoStoreManagementApi.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool>("PrimaryAdress")
                        .HasColumnType("bit");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Zipcode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Area = "Downtown",
                            City = "CityA",
                            CustomerId = 101,
                            PrimaryAdress = true,
                            State = "StateA",
                            Zipcode = 12345
                        },
                        new
                        {
                            Id = 2,
                            Area = "Uptown",
                            City = "CityB",
                            CustomerId = 102,
                            PrimaryAdress = false,
                            State = "StateB",
                            Zipcode = 54321
                        });
                });

            modelBuilder.Entity("VideoStoreManagementApi.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<float>("TotalPrice")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 101,
                            TotalPrice = 19.99f
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 102,
                            TotalPrice = 29.98f
                        });
                });

            modelBuilder.Entity("VideoStoreManagementApi.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<int>("VideoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VideoId");

                    b.HasIndex("CartId", "VideoId")
                        .IsUnique();

                    b.ToTable("CartItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CartId = 1,
                            Price = 19.99f,
                            Qty = 1,
                            VideoId = 1
                        },
                        new
                        {
                            Id = 2,
                            CartId = 2,
                            Price = 29.98f,
                            Qty = 2,
                            VideoId = 2
                        });
                });

            modelBuilder.Entity("VideoStoreManagementApi.Models.Customer", b =>
                {
                    b.Property<int>("Uid")
                        .HasColumnType("int");

                    b.Property<string>("MembershipType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Uid");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Uid = 101,
                            MembershipType = "Basic"
                        },
                        new
                        {
                            Uid = 102,
                            MembershipType = "Premium"
                        },
                        new
                        {
                            Uid = 100,
                            MembershipType = "Premium"
                        });
                });

            modelBuilder.Entity("VideoStoreManagementApi.Models.Inventory", b =>
                {
                    b.Property<int>("VideoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("VideoId");

                    b.ToTable("Inventories");

                    b.HasData(
                        new
                        {
                            VideoId = 1,
                            LastUpdate = new DateTime(2024, 5, 29, 21, 59, 33, 162, DateTimeKind.Local).AddTicks(9831),
                            Stock = 10
                        },
                        new
                        {
                            VideoId = 2,
                            LastUpdate = new DateTime(2024, 5, 28, 21, 59, 33, 162, DateTimeKind.Local).AddTicks(9840),
                            Stock = 5
                        });
                });

            modelBuilder.Entity("VideoStoreManagementApi.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("DeliveryAddressId")
                        .HasColumnType("int");

                    b.Property<string>("DeliveryStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpectedDeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OrderedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("PaymentDone")
                        .HasColumnType("bit");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RealDeliveredDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RentalOrPermanent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("TotalAmount")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DeliveryAddressId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 101,
                            DeliveryAddressId = 1,
                            DeliveryStatus = "Delivered",
                            ExpectedDeliveryDate = new DateTime(2024, 6, 4, 21, 59, 33, 162, DateTimeKind.Local).AddTicks(9879),
                            OrderedDate = new DateTime(2024, 5, 20, 21, 59, 33, 162, DateTimeKind.Local).AddTicks(9878),
                            PaymentDone = true,
                            PaymentType = "COD",
                            RentalOrPermanent = "Rental",
                            TotalAmount = 0f
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 102,
                            DeliveryAddressId = 2,
                            DeliveryStatus = "Delivered",
                            ExpectedDeliveryDate = new DateTime(2024, 6, 9, 21, 59, 33, 162, DateTimeKind.Local).AddTicks(9881),
                            OrderedDate = new DateTime(2024, 5, 10, 21, 59, 33, 162, DateTimeKind.Local).AddTicks(9880),
                            PaymentDone = false,
                            PaymentType = "COD",
                            RentalOrPermanent = "Permanent",
                            TotalAmount = 0f
                        });
                });

            modelBuilder.Entity("VideoStoreManagementApi.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<int>("VideoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("VideoId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            Price = 19.99f,
                            Qty = 1,
                            VideoId = 1
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 2,
                            Price = 29.98f,
                            Qty = 2,
                            VideoId = 2
                        });
                });

            modelBuilder.Entity("VideoStoreManagementApi.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("PaymentSucess")
                        .HasColumnType("bit");

                    b.Property<int>("TransactionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("TransactionId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("VideoStoreManagementApi.Models.Permanent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<float>("TotalPrice")
                        .HasColumnType("real");

                    b.Property<int>("TotalQty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Permanents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 2,
                            TotalPrice = 29.98f,
                            TotalQty = 2
                        });
                });

            modelBuilder.Entity("VideoStoreManagementApi.Models.Rental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("LateFee")
                        .HasColumnType("real");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("TotalPrice")
                        .HasColumnType("real");

                    b.Property<int>("TotalQty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Rentals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DueDate = new DateTime(2024, 5, 31, 21, 59, 33, 162, DateTimeKind.Local).AddTicks(9922),
                            LateFee = 0f,
                            OrderId = 1,
                            RentDate = new DateTime(2024, 5, 21, 21, 59, 33, 162, DateTimeKind.Local).AddTicks(9921),
                            ReturnDate = new DateTime(2024, 5, 30, 21, 59, 33, 162, DateTimeKind.Local).AddTicks(9923),
                            TotalPrice = 19.99f,
                            TotalQty = 1
                        });
                });

            modelBuilder.Entity("VideoStoreManagementApi.Models.User", b =>
                {
                    b.Property<int>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Uid"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Password")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("Verified")
                        .HasColumnType("bit");

                    b.HasKey("Uid");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Uid = 101,
                            Email = "test1@gmail.com",
                            FirstName = "test1",
                            LastName = "test",
                            Password = new byte[] { 123, 239, 43, 120, 46, 211, 34, 46, 152, 172, 118, 153, 179, 233, 180, 219, 81, 98, 170, 232, 9, 158, 116, 32, 169, 156, 85, 50, 216, 66, 48, 230, 171, 100, 42, 183, 149, 187, 39, 100, 23, 41, 83, 239, 92, 40, 200, 206, 63, 22, 237, 12, 152, 68, 167, 25, 184, 4, 180, 107, 152, 199, 89, 121 },
                            Role = "Customer",
                            Salt = new byte[] { 207, 70, 239, 202, 195, 152, 239, 190, 240, 191, 82, 94, 207, 63, 65, 144, 214, 104, 69, 9, 151, 141, 198, 75, 72, 6, 63, 112, 189, 119, 173, 4, 122, 138, 86, 201, 21, 242, 31, 68, 206, 11, 222, 145, 11, 70, 134, 195, 86, 94, 230, 82, 252, 240, 158, 132, 143, 44, 62, 60, 30, 92, 211, 183, 111, 224, 229, 156, 204, 110, 182, 175, 191, 201, 47, 3, 109, 22, 145, 75, 230, 109, 40, 165, 189, 213, 77, 50, 23, 99, 157, 24, 169, 117, 91, 120, 27, 248, 112, 161, 120, 150, 120, 69, 228, 248, 165, 2, 41, 61, 62, 248, 207, 54, 146, 255, 65, 184, 211, 205, 254, 13, 250, 202, 196, 176, 76, 60 },
                            Verified = true
                        },
                        new
                        {
                            Uid = 102,
                            Email = "test2@gmail.com",
                            FirstName = "test2",
                            LastName = "test",
                            Password = new byte[] { 123, 239, 43, 120, 46, 211, 34, 46, 152, 172, 118, 153, 179, 233, 180, 219, 81, 98, 170, 232, 9, 158, 116, 32, 169, 156, 85, 50, 216, 66, 48, 230, 171, 100, 42, 183, 149, 187, 39, 100, 23, 41, 83, 239, 92, 40, 200, 206, 63, 22, 237, 12, 152, 68, 167, 25, 184, 4, 180, 107, 152, 199, 89, 121 },
                            Role = "Customer",
                            Salt = new byte[] { 207, 70, 239, 202, 195, 152, 239, 190, 240, 191, 82, 94, 207, 63, 65, 144, 214, 104, 69, 9, 151, 141, 198, 75, 72, 6, 63, 112, 189, 119, 173, 4, 122, 138, 86, 201, 21, 242, 31, 68, 206, 11, 222, 145, 11, 70, 134, 195, 86, 94, 230, 82, 252, 240, 158, 132, 143, 44, 62, 60, 30, 92, 211, 183, 111, 224, 229, 156, 204, 110, 182, 175, 191, 201, 47, 3, 109, 22, 145, 75, 230, 109, 40, 165, 189, 213, 77, 50, 23, 99, 157, 24, 169, 117, 91, 120, 27, 248, 112, 161, 120, 150, 120, 69, 228, 248, 165, 2, 41, 61, 62, 248, 207, 54, 146, 255, 65, 184, 211, 205, 254, 13, 250, 202, 196, 176, 76, 60 },
                            Verified = true
                        },
                        new
                        {
                            Uid = 100,
                            Email = "admin@gmail.com",
                            FirstName = "admin",
                            LastName = "admin",
                            Password = new byte[] { 149, 237, 106, 116, 11, 217, 77, 175, 193, 26, 2, 95, 243, 29, 43, 61, 69, 201, 153, 145, 47, 253, 156, 255, 16, 34, 47, 124, 27, 249, 104, 186, 247, 22, 54, 177, 190, 100, 37, 95, 247, 253, 0, 11, 234, 42, 174, 34, 68, 214, 9, 180, 165, 51, 165, 153, 124, 242, 71, 210, 212, 185, 244, 129 },
                            Role = "Admin",
                            Salt = new byte[] { 207, 70, 239, 202, 195, 152, 239, 190, 240, 191, 82, 94, 207, 63, 65, 144, 214, 104, 69, 9, 151, 141, 198, 75, 72, 6, 63, 112, 189, 119, 173, 4, 122, 138, 86, 201, 21, 242, 31, 68, 206, 11, 222, 145, 11, 70, 134, 195, 86, 94, 230, 82, 252, 240, 158, 132, 143, 44, 62, 60, 30, 92, 211, 183, 111, 224, 229, 156, 204, 110, 182, 175, 191, 201, 47, 3, 109, 22, 145, 75, 230, 109, 40, 165, 189, 213, 77, 50, 23, 99, 157, 24, 169, 117, 91, 120, 27, 248, 112, 161, 120, 150, 120, 69, 228, 248, 165, 2, 41, 61, 62, 248, 207, 54, 146, 255, 65, 184, 211, 205, 254, 13, 250, 202, 196, 176, 76, 60 },
                            Verified = true
                        });
                });

            modelBuilder.Entity("VideoStoreManagementApi.Models.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tittle")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Tittle")
                        .IsUnique();

                    b.ToTable("Videos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "At Mr. Rad's Warehouse, the best hip-hop crews in Los Angeles compete for money and respect.",
                            Director = "Director 1",
                            Genre = "Action",
                            Price = 19.99f,
                            ReleaseDate = new DateTime(2023, 5, 30, 21, 59, 33, 162, DateTimeKind.Local).AddTicks(9799),
                            Tittle = "Action Movie"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A basketball player's father must try to convince him to go to a college so he can get a shorter sentence.",
                            Director = "Director 2",
                            Genre = "Comedy",
                            Price = 14.99f,
                            ReleaseDate = new DateTime(2022, 5, 30, 21, 59, 33, 162, DateTimeKind.Local).AddTicks(9815),
                            Tittle = "Comedy Movie"
                        });
                });

            modelBuilder.Entity("VideoStoreManagementApi.Models.Address", b =>
                {
                    b.HasOne("VideoStoreManagementApi.Models.Customer", "Customer")
                        .WithMany("Address")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("VideoStoreManagementApi.Models.Cart", b =>
                {
                    b.HasOne("VideoStoreManagementApi.Models.Customer", "Customer")
                        .WithOne()
                        .HasForeignKey("VideoStoreManagementApi.Models.Cart", "CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("VideoStoreManagementApi.Models.CartItem", b =>
                {
                    b.HasOne("VideoStoreManagementApi.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VideoStoreManagementApi.Models.Video", "Video")
                        .WithMany()
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("VideoStoreManagementApi.Models.Customer", b =>
                {
                    b.HasOne("VideoStoreManagementApi.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("VideoStoreManagementApi.Models.Customer", "Uid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VideoStoreManagementApi.Models.Inventory", b =>
                {
                    b.HasOne("VideoStoreManagementApi.Models.Video", "Video")
                        .WithOne()
                        .HasForeignKey("VideoStoreManagementApi.Models.Inventory", "VideoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("VideoStoreManagementApi.Models.Order", b =>
                {
                    b.HasOne("VideoStoreManagementApi.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VideoStoreManagementApi.Models.Address", "DeliveryAddress")
                        .WithMany()
                        .HasForeignKey("DeliveryAddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("DeliveryAddress");
                });

            modelBuilder.Entity("VideoStoreManagementApi.Models.OrderItem", b =>
                {
                    b.HasOne("VideoStoreManagementApi.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VideoStoreManagementApi.Models.Video", "Video")
                        .WithMany()
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("VideoStoreManagementApi.Models.Payment", b =>
                {
                    b.HasOne("VideoStoreManagementApi.Models.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("VideoStoreManagementApi.Models.Permanent", b =>
                {
                    b.HasOne("VideoStoreManagementApi.Models.Order", "Order")
                        .WithOne("Permanent")
                        .HasForeignKey("VideoStoreManagementApi.Models.Permanent", "OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("VideoStoreManagementApi.Models.Rental", b =>
                {
                    b.HasOne("VideoStoreManagementApi.Models.Order", "Order")
                        .WithOne("Rental")
                        .HasForeignKey("VideoStoreManagementApi.Models.Rental", "OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("VideoStoreManagementApi.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("VideoStoreManagementApi.Models.Customer", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("VideoStoreManagementApi.Models.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Payments");

                    b.Navigation("Permanent")
                        .IsRequired();

                    b.Navigation("Rental")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
